apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: projects
    repoURL: git@github.com:dipbhujbal/inception-managed-argocd.git 
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - createNamespace=true
    automated:
      prune: true
      selfHeal: true
