apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    avp.kubernetes.io/path: "argo-app-secrets/show/repo-secrets"
stringData:
  type: <type>
  url: <url>
  sshPrivateKey: <ssh-private-key>
    
